name: dart_basic
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  path: ^1.8.3
  rxdart: ^0.27.3
  meta: ^1.11.0 
  date_format: ^2.0.6

dev_dependencies:
  lints: ^3.0.0
